# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Instance Name')),
                ('type', models.CharField(max_length=30, verbose_name='Instance Type')),
                ('aws_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Subnet Name')),
                ('cidr', models.CharField(max_length=30, verbose_name='Subnet CIDR')),
                ('availability_zone', models.CharField(default='', max_length=30)),
                ('aws_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vpc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Vpc Name')),
                ('cidr', models.CharField(max_length=30, verbose_name='Vpc CIDR')),
                ('region', models.CharField(default='', max_length=30)),
                ('aws_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='subnet',
            name='vpc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.Vpc'),
        ),
        migrations.AddField(
            model_name='instance',
            name='subnet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.Subnet'),
        ),
    ]
